all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: ec2-35-90-234-7.us-west-2.compute.amazonaws.com
        server-two:
          ansible_host: ec2-52-10-19-104.us-west-2.compute.amazonaws.com
      
